global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'event_service'
    static_configs:
      - targets: ['event_service:8002']  # Убедитесь, что это правильный порт для вашего event_service
